import os
import re

file_colors = r'C:\Users\ruzaq\AndroidStudioProjects\MOCCA\composeApp\src\commonMain\kotlin\com\mocca\app\ui\theme\AppColors.kt'
with open(file_colors, 'r', encoding='utf-8') as f:
    content = f.read()

# Inject Anchor fields into AppColors
inject_anchors = '''@Immutable
object AppColors {
    // ---------------------------------------------------------------------------
    // BRAND ANCHOR COLORS
    // ---------------------------------------------------------------------------
    val AnchorPrimary = Color(0xFF8B9DC3)
    val AnchorSecondary = Color(0xFF8B9DC3)
    val AnchorTertiary = Color(0xFF8B9DC3)
    val DarkBackgroundSeed = Color(0xFF1A1A1A)
'''

content = re.sub(r'@Immutable\s*object AppColors \{', inject_anchors, content)

with open(file_colors, 'w', encoding='utf-8') as f:
    f.write(content)


file_theme = r'C:\Users\ruzaq\AndroidStudioProjects\MOCCA\composeApp\src\commonMain\kotlin\com\mocca\app\ui\theme\AppTheme.kt'
with open(file_theme, 'r', encoding='utf-8') as f:
    content = f.read()

# Replace AppColorScheme
new_scheme = '''private val AppColorScheme: ColorScheme = darkColorScheme(
    primary = AppColors.AnchorPrimary,
    secondary = AppColors.AnchorSecondary,
    tertiary = AppColors.AnchorTertiary,
    background = AppColors.DarkBackgroundSeed,
    surface = AppColors.DarkBackgroundSeed,
    // Note: The rest of the scheme is generated by M3 internally.
)'''

content = re.sub(r'private val AppColorScheme: ColorScheme = darkColorScheme\([^)]+\)', new_scheme, content, flags=re.MULTILINE|re.DOTALL)

with open(file_theme, 'w', encoding='utf-8') as f:
    f.write(content)
